apiVersion: v1
kind: Namespace
metadata:
  name: marathontabelle
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: marathontabelle
  name: marathontabelle
  namespace: marathontabelle
spec:
  replicas: 1
  selector:
    matchLabels:
      run: marathontabelle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: marathontabelle
    spec:
      containers:
      - image: koa1/marathontabelle:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: marathontabelle
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
            cpu: "1"          
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - name: web
          containerPort: 8080
        volumeMounts:
        - mountPath: "/root/marathon-data"
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim: 
          claimName: marathon-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: marathontabelle
  name: marathontabelle
  namespace: marathontabelle
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: marathontabelle
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: marathontabelle
  namespace: marathontabelle
  labels:
    app: marathontabelle
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "false"
spec:
  tls:
  - hosts:
    - marathontabelle.lkw.teamkoenig.ch
    secretName: marathontabelle.lkw.teamkoenig.ch-tls
  rules:
  - host: marathontabelle.lkw.teamkoenig.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: marathontabelle
          servicePort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: marathontabelle
  name: marathon-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


